services:
  # Core PHP App Engine
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: eco_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html:ro
      - ./web/public:/var/www/html/public
    env_file:
      - .env