apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eco-marketplace-ingress
  namespace: eco-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 🍪 CONFIGURACIÓN CRÍTICA DE STICKY SESSIONS
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "ECO_MARKET_AFFINITY"
    nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    # Soporte SSL/HTTPS detrás de Cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  rules:
  - host: "ecomercio.cl"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eco-web-service # <-- Asegúrate de que coincida con el nombre de tu Service en K8s
            port:
              number: 80