apiVersion: v1
kind: Secret
metadata:
  name: eco-marketplace-secrets
  namespace: eco-prod
type: Opaque
stringData:
  # CHANGE THIS LINE: Ensure it uses the correct internal ClusterIP or correct domain
  db-host: "mariadb-service.default.svc.cluster.local"  
  db-name: "eco_classifieds"
  db-user: "user_prod_eco"
  db-pass: "U80wrNQF2r4V8F5109FD"